### ISSUE TITLE
Timeseries search and asset search look very different

### ISSUE THREAD

**Issue by anderscognite** [cognitedata/gearbox.js#287] opened 2019-06-04 16:58 UTC
The time series search is much nicer than the asset search as it gives a more permanent list (compared to dropdown). I think both views should be available for both components.

**Comment by mrtraser** [comment] 2019-06-10 07:44
They look different because of different functional and usage scenarios, you don't need any checkbox or additional info when you searching for an asset by name. For TimeseriesSearch you need to have ability choose few elements from list by design. There is no reason to extend components with unused (unneeded by design) functional.

**Comment by anderscognite** [comment] 2019-06-10 07:51
Search result that is not a drop down is very useful.

**Comment by anderscognite** [comment] 2019-06-10 07:54
And is in fact used in OpInt!

**Comment by mrtraser** [comment] 2019-06-10 08:01
If you select one of founded result you'll get full asset description.

> Search result that is not a drop down is very useful

It is possible to add `onSearch` callback that will contain full list of founded assets (that is present in dropdown list). You'll be able to implement your own "drop down" in any way you want.

**Comment by mrtraser** [comment] 2019-06-10 08:06
@anderscognite , will be above solution flexible enough to implement similar behavior that we have in OpInt?

**Comment by anderscognite** [comment] 2019-06-10 08:14
I have already implemented something like that in my application just using <Input> hehe. I still think it would be a useful component here (maybe with an improved version of the filter options that they have there).

**Comment by mrtraser** [comment] 2019-06-10 08:32
There are no strong requirements for this component and cases where it will use, so it will be always a few things to improve or nice to have. My idea is to provide basic usage component "right out the box" and a wide range of additional callbacks that provide information in different component states that help user to reuse this info inside the application.

We can't have the same version of asset search as in OpInt (which is implemented like a column) cause someone would like to implement it in a raw (like in OpSupport, near scanner icon in top right corner).

I'll add `onSearchResult` and `dropdownList`props to have more flexible control under the component, that we have now. (I guess these two props give you enough possibility to implement actually the same component as in OpInt)

**Comment by anderscognite** [comment] 2019-06-10 08:37
Allright, sounds good :) As long as it is possible to use it without dropdown menu (so it's basically an <Input> with callback with data, it should solve many things!

**Comment by mrtraser** [comment] 2019-06-10 08:38
Deal :)

**Comment by mrtraser** [comment] 2019-06-13 12:06
Fixed in #329

**Closed by mrtraser** 2019-06-13 12:06 UTC
